---
- name: Add nginx.repo
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Install nginx
  yum: name=nginx state=present

- name: nginx service state
  service: name=nginx state=started enabled=yes

- name: Create ssl directory
  file: state=directory path={{ssl_dir}} owner={{host_user}} group={{host_user}}

- name: Add private key to ssl
  copy: src=domain.key dest={{ssl_dir}}/domain.key mode=0644

- name: Add public crt to ssl
  copy: src=bundle.crt dest={{ssl_dir}}/bundle.crt mode=0644

- name: Copy default nginx conf
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf mode=0644
  
- name: Reloaded nginx
  service: name=nginx state=reloaded enabled=yes